### ISSUE TITLE
def skel_pruning_DSE(skel, dist, min_area_px=100):

### ISSUE THREAD

**Issue by lsx1980** [originlake/DSE#1]
AttributeError: 'MultiGraph' object has no attribute 'node'
raceback (most recent call last):
  File "example.py", line 26, in <module>
    new_skel = skel_pruning_DSE(skel, dist, 100)
  File "/home/suxing/DSE-skeleton-pruning/dsepruning/dsepruning.py", line 122, in skel_pruning_DSE
    pts.append(graph.node[s]['o'].astype(np.int32).tolist())
AttributeError: 'MultiGraph' object has no attribute 'node'

**Comment by originlake** [comment]
Networkx seems to have backward compatibility issues, could you try
```
pip uninstall networkx
pip install networkx==2.3
```

**Comment by lsx1980** [comment]
Hi, thanks for your reply. I have tried with your suggestion above, same error.

**Comment by originlake** [comment]
Try the latest commit, should work with networkx>2.3. Remember to follow readme.md to build it first

**Comment by lsx1980** [comment]
Thank you, it works now, add "pip install Cython" and build "python3 setup.py build_ext --inplace" solved the problem.  Results looks promising.
